spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL:jdbc:mariadb://localhost:3306/ExpenseTracker}
    username: ${DB_USER:myuser}
    password: ${DB_PASS:abc123}
  liquibase:
    change-log: classpath:liquibase/db/changelog/changelog.xml
  jpa:
    open-in-view: false
jwt:
  secret-key: my-secret-key-for-jwt-token
